### ISSUE TITLE
[FEATURE REQUEST] General Code Cleanup

### ISSUE THREAD

**Issue by flancast90** [Reiningecho90/Ctrl-V-Plus-Plus#2]
Hey, just saw your project on Reddit! I don't have the time to contribute code, but here's some general cleanup ideas I can see. 

Line 81-121: function listener - change to a for loop, I don't see a need to do 10 different if/else statements. Same for lines 123-152

(General) Metaclass - Is there a reason you are using the nested classes? Something useful for debugging and readability is to have separate classes, or even each class in a separate file. As to your conflict, I think that it is because of the way you are passing your arts to the class. Take a look at https://stackoverflow.com/a/25191150. 

Lastly, about making the program more intuitive, is there a need for separate CTRL+C/V+{num} clicks? In my opinion, it is more understandable to use the default CTRL+C and store the last 10 values from that in your dictionary. As an end user, I think I would forget which number I was on in the clipboard using your method.

**Comment by Reiningecho90** [comment]
Working on this request now, should go hand in hand with #1 , fixes are going to be posted where necessary.

Changes being worked through:
1.  Streamlining class structure
2. Fixing listener code (reformatting to for loop)
3. Applying the GUI to streamline the use cases

**Comment by Reiningecho90** [comment]
These fixes were made:
1. Class structure was streamlined to a single class (see cv++_main.py lines 18-87)
2. Reformatted listener code into for loops (see cv++_main.py lines 62-87)
3. Removed boolean values which were causing issues deep within Python, TKinter GUI will get a fix (this may re-open)
