### ISSUE TITLE
[FEATURE REQUEST] Remove unneeded print() statements.

### ISSUE THREAD

**Issue by flancast90** [Reiningecho90/Ctrl-V-Plus-Plus#6]
As the title says, the print() statements with all branches of the repo are unneeded and distracting. A better alternative is the native [``logging`` library](https://docs.python.org/3/library/logging.html), which is much more customizable, and recommended for debugging. (See below excerpt)

> The main reason printing is not the ideal solution for logging is because printing does not provide a timestamp of when the error occurred.
> 
> Knowing exactly when the error occurred can prove to be an important factor while debugging an application. It might not be as critical for small packets of code that can be run and tested in real-time, but larger applications without an error timestamp will have some serious consequences. One option would be to add the datetime module for that extra information, but this creates a very messy codebase.
[source](https://www.logicmonitor.com/blog/python-logging-levels-explained) 

Some reasons ``logging`` is better for keeping track of loops that fire/fail is that they can be set at different levels (e.g. ``loglevel=DEBUG`` will not catch non-debugging errors ``info, warning, etc``). This also means that users of the program will have a clean interface, while still allowing developers to easily diagnose problems.

**Comment by flancast90** [comment]
Proposed in #7 @Reiningecho90

**Comment by Reiningecho90** [comment]
Working on #7 now, thanks.
